name: Build APK
on: [workflow_dispatch]

jobs:
  build:
    # Cambiamos a windows-2022 que tiene Visual Studio 2022 y entiende Android 13/14/15
    runs-on: windows-2022 
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore Packages
        run: nuget restore PKHeX.Mobile.sln

      - name: Build Android
        # Usamos la ruta corregida que verificamos antes
        run: msbuild PKHeX.Android/PKHeX.Android.csproj /p:Configuration=Release /t:PackageForAndroid /p:AndroidBuildApplicationPackage=true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PKHeX-Classic-APK
          path: PKHeX.Android/bin/Release/*.apk
